name: Slither
on: [push]
jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
      - run: pip3 install slither-analyzer
      - run: slither src/ --exclude-dependencies || true
